image: node:9.9.0

pipelines:
  default:
    - step:
        name: Tests
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run type-check
          - npm test
